### ISSUE TITLE
Release of trained models

### ISSUE THREAD

**Issue by gmberton** [quqixun/BioMassters#1]
Thank you for the amazing repo!
Are you planning to release the trained models?

**Comment by quqixun** [comment]
I have released the trained model. Please see [README](https://github.com/quqixun/BioMassters#4-training).
I uploaded models to BaiduDisc only, I always fail to upload them to GoogleDrive or OneDrive due to the unstable VPN.

**Comment by gmberton** [comment]
I didn't see the link to the trained model, thanks!
However somehow I can't download it from BaiduDisc, the downloading isn't working properly, and I can't understand why.
Could you upload it to torch.hub, as a GitHub tag? Or if you find a way to send it to me, I could host it on my GoogleDrive

**Comment by quqixun** [comment]
> Or if you find a way to send it to me, I could host it on my GoogleDrive

I will find a way, please wait for a while.

**Comment by quqixun** [comment]
@gmberton 
I have uploaded models to MEGA, please have a try.
- Trained model: [MEGA link](https://mega.nz/file/XNpWBZSY#rkA2O5JsR6TZ_xfqS3TV4I0V_xs76ni9_2PlFmfhUh8)
- Prediction of public testing dataset: [MEGA link](https://mega.nz/file/6M410TRY#ozfptCWDvYatZHMAm18uOayYDwAZSAw3U-ZfxAONLN8)

**Comment by gmberton** [comment]
That works perfectly, thanks! Would you like me to host it on GDrive?

**Comment by quqixun** [comment]
> That works perfectly, thanks! Would you like me to host it on GDrive?

That would be great!

Could you please test the trained models first to check their integrity?
I uploaded those models for several hours, I am not sure if models could work as expected.

If everything is fine, prediction of public testing dataset should be same as the one on the MEGA.
Then, please upload models to GDrive and modify README in a PR.
Thanks.

**Comment by gmberton** [comment]
Sure, I will do the PR.
In the meantime, these are the cksums that I get for each file:
```
3809319375 6942 fold0/logs.csv
2691143627 533224127 fold0/model.pth
4264114490 7699 fold1/logs.csv
3205302331 533224127 fold1/model.pth
3014148841 7700 fold2/logs.csv
224337152 533224127 fold2/model.pth
1721957316 7531 fold3/logs.csv
634312061 533224127 fold3/model.pth
2789717063 6180 fold4/logs.csv
2659525392 533224127 fold4/model.pth
```
Can you confirm if they're correct?

**Comment by quqixun** [comment]
Here is cksums of my local model :
```
3809319375 6942 ./fold0/logs.csv
2691143627 533224127 ./fold0/model.pth
4264114490 7699 ./fold1/logs.csv
3205302331 533224127 ./fold1/model.pth
3014148841 7700 ./fold2/logs.csv
224337152 533224127 ./fold2/model.pth
1721957316 7531 ./fold3/logs.csv
634312061 533224127 ./fold3/model.pth
2789717063 6180 ./fold4/logs.csv
2659525392 533224127 ./fold4/model.pth
```
They are exactly same as yours.

**Comment by quqixun** [comment]
@gmberton Thanks for uploading model to GoogleDrive.
I will close the issue.
